[package]
name = "szrsql-dist"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "SzRSQL 分布式：Raft/2PC/Percolator"

[dependencies]
szrsql-types = { workspace = true }
szrsql-tx = { workspace = true }
szrsql-cdc = { workspace = true }
szrsql-replication = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
