[package]
name = "szrsql-optimizer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "SzRSQL 查询优化器：CBO/RBO/Morsel-Driven"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
szrsql-types = { workspace = true }
szrsql-sql = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
